[versions]
agp = "8.13.2"
androidSdk = "2.6.0"
installreferrer = "2.2"
kotlin = "2.2.20"
coreKtx = "1.17.0"
kotlinxCoroutinesCore = "1.9.0"
ktor = "2.3.7"
lifecycle-version = "2.10.0"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
coil = "2.2.2"
gson = "2.12.0"
playServicesAdsIdentifier = "18.0.1"
room = "2.8.0"
data-store = '1.1.7'
okhttp = "4.11.0"
koin_version = "4.1.1"
material3 = "1.4.0"
serialization-json = "1.9.0"
slf4jSimple = "2.0.16"
foundation = "1.11.0"

[libraries]
android-sdk = { module = "io.adtrace:android-sdk", version.ref = "androidSdk" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-version" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-version" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-version" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-version" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-version" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }

ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }


coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
koin-android = { module = "io.insert-koin:koin-android" , version.ref = "koin_version"}
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" , version.ref = "koin_version"}

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-data-store = { group = "androidx.datastore", name = "datastore-preferences",  version.ref = "data-store"}

compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "core", version = "2.2.0" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version = "2.2.0" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp" }

