## Add project specific ProGuard rules here.
## You can control the set of applied configuration files using the
## proguardFiles setting in build.gradle.
##
## For more details, see
##   http://developer.android.com/guide/developing/tools/proguard.html
#
## If your project uses WebView with JS, uncomment the following
## and specify the fully qualified class name to the JavaScript interface
## class:
##-keepclassmembers class fqcn.of.javascript.interface.for.webview {
##   public *;
##}
#
## Uncomment this to preserve the line number information for
## debugging stack traces.
##-keepattributes SourceFile,LineNumberTable
#
## If you keep the line number information, uncomment this to
## hide the original source file name.
##-renamesourcefileattribute SourceFile
#
## Keep all use cases
#-keep class com.numtory.domain.enums.** { *; }
#
## Keep coroutines
#-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
#-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
#-keepclassmembers class kotlinx.coroutines.** {
#    volatile <fields>;
#}
#
## Keep Retrofit
#-keepattributes Signature
#-keepattributes Exceptions
#-keep class retrofit2.** { *; }
#-keepclasseswithmembers class * {
#    @retrofit2.http.* <methods>;
#}
#
## Keep Gson models
#-keep class com.yourpackage.models.** { *; }
#-keepclassmembers class com.yourpackage.models.** {
#    *** *();
#}
#
## Keep all classes with @Serializable annotation
#-keep @kotlinx.serialization.Serializable class *
#-keepclassmembers class * {
#    @kotlinx.serialization.Serializable <fields>;
#}
#
## Keep all companion objects (for .serializer() calls)
#-keepclassmembers class * {
#    static *** serializer(...);
#}
#
## Keep your use cases
#-keep class com.yourpackage.domain.usecase.** { *; }
#
## Keep Flow and coroutines
#-keep class kotlinx.coroutines.flow.** { *; }
#-keepclassmembers class kotlinx.coroutines.flow.** {
#    *** collect(...);
#}
#
## Generated by R8 when it detects missing runtime dependencies
#-keep class kotlinx.serialization.json.Json {
#    public *** encodeToString(...);
#    public *** decodeFromString(...);
#}
#-keep class com.numtory.application.features.market.data.models.ExchangeInfoDataModel$$serializer {
#    public static final  com.numtory.application.features.market.data.models.ExchangeInfoDataModel$$serializer INSTANCE;
#}
#-keepclassmembers class  com.numtory.application.features.market.data.models.ExchangeInfoDataModel {
#    *** Companion;
#}

