package com.numtory.application.features.cryptoMarket.domain.entities

val cryptoMap = mutableMapOf(
    "BTC" to "Bitcoin",
    "ETH" to "Ethereum",
    "USDT" to "Tether",
    "PAXG" to "PAX Gold | طلا دیجیتال",
    "USOON" to "Oil | نفت دیجیتال",
    "SLVON" to "Silver | نقره دیجیتال",
    "COPXON" to "Coper | مس دیجیتال",
    "XRP" to "Ripple",
    "SOL" to "Solana",
    "BNB" to "Binance Coin",
    "USDC" to "USD Coin",
    "TRX" to "TRON",
    "DOGE" to "Dogecoin",
    "ADA" to "Cardano",
    "USDS" to "USDS",
    "BCH" to "Bitcoin Cash",
    "WBTC" to "Wrapped Bitcoin",
    "LINK" to "Chainlink",
    "ZEC" to "Zcash",
    "XMR" to "Monero",
    "XLM" to "Stellar",
    "SUI" to "Sui",
    "LTC" to "Litecoin",
    "LSK" to "Lisk",
    "HYPE" to "Hyperliquid",
    "USDE" to "USDe",
    "AVAX" to "Avalanche",
    "ADI" to "Adi",
    "HBAR" to "Hedera",
    "NIL" to "Nil",
    "SHIB" to "Shiba Inu",
    "PIPPIN" to "Pippin",
    "CC" to "CC",
    "SNT" to "Status",
    "WLFI" to "WLFI",
    "TON" to "Toncoin",
    "DAI" to "Dai",
    "CRO" to "Cronos",
    "UNI" to "Uniswap",
    "DOT" to "Polkadot",
    "XAGX" to "Silver Token",
    "MNT" to "Mantle",
    "USD1" to "USD1",
    "PEPE" to "Pepe",
    "TAO" to "Bittensor",
    "AAVE" to "Aave",
    "RAVE" to "Rave",
    "BGB" to "Bitget Token",
    "OKB" to "OKB",
    "XAUT" to "Tether Gold",
    "NEAR" to "NEAR Protocol",
    "ETC" to "Ethereum Classic",
    "GSON" to "Gold Standard",
    "PALLON" to "Palladium Token",
    "GLDON" to "Gold Token",
    "PEPON" to "Pepon",
    "JPMON" to "JPMorgan Token",
    "NKEON" to "Nike Token",
    "MCDON" to "McDonald's Token",
    "GEON" to "General Electric Token",
    "AAPLON" to "Apple Token",
    "FON" to "Ford Token",
    "ENA" to "Ethena",
    "ICP" to "Internet Computer",
    "ASTER" to "Aster",
    "WLD" to "Worldcoin",
    "KCS" to "KuCoin Token",
    "APT" to "Aptos",
    "SKY" to "Sky",
    "PUMP" to "Pump",
    "ONDO" to "Ondo",
    "KAS" to "Kaspa",
    "POL" to "Polygon",
    "NIGHT" to "Night",
    "ARB" to "Arbitrum",
    "ALGO" to "Algorand",
    "RENDER" to "Render",
    "ATOM" to "Cosmos",
    "FIL" to "Filecoin",
    "QNT" to "Quant",
    "VET" to "VeChain",
    "BONK" to "Bonk",
    "FLR" to "Flare",
    "XDC" to "XDC Network",
    "NEXO" to "Nexo",
    "SIREN" to "Siren",
    "SEI" to "Sei",
    "STABLE" to "Stable",
    "PENGU" to "Pudgy Penguins",
    "VIRTUAL" to "Virtual Protocol",
    "JUP" to "Jupiter",
    "IP" to "IP",
    "CAKE" to "PancakeSwap",
    "BDX" to "Beldex",
    "FET" to "Fetch.ai",
    "MORPHO" to "Morpho",
    "OP" to "Optimism",
    "CRV" to "Curve DAO Token",
    "XTZ" to "Tezos",
    "SPX" to "SPX",
    "DASH" to "Dash",
    "FLOKI" to "Floki Inu",
    "LDO" to "Lido DAO",
    "AERO" to "Aerodrome",
    "INJ" to "Injective",
    "SKYAI" to "SkyAI",
    "ETHFI" to "Ether.fi",
    "FDUSD" to "First Digital USD",
    "TIA" to "Celestia",
    "STRK" to "Strike",
    "IOTA" to "IOTA",
    "XCN" to "Chain",
    "VVV" to "VVV",
    "CHZ" to "Chiliz",
    "SYRUP" to "Syrup",
    "GRT" to "The Graph",
    "FARTCOIN" to "Fartcoin",
    "2Z" to "2Z",
    "JASMY" to "JasmyCoin",
    "CFX" to "Conflux",
    "ENS" to "Ethereum Name Service",
    "WIF" to "Dogwifhat",
    "PYTH" to "Pyth Network",
    "JST" to "JUST",
    "XPL" to "XPL",
    "EDGE" to "Edge",
    "KAIA" to "Kaia",
    "TWT" to "Trust Wallet Token",
    "PENDLE" to "Pendle",
    "LIGHTER" to "Lighter",
    "SUN" to "Sun",
    "TEL" to "Telcoin",
    "S" to "Sonic",
    "NFT" to "NFT",
    "GALA" to "Gala",
    "ZK" to "zkSync",
    "BAT" to "Basic Attention Token",
    "SAND" to "The Sandbox",
    "RAY" to "Raydium",
    "THETA" to "Theta Network",
    "VSN" to "VSN",
    "BUSD" to "BUSD",
    "CMC20" to "CMC20",
    "MON" to "Mon",
    "A" to "A",
    "HNT" to "Helium",
    "SENT" to "Sent",
    "ZBCN" to "Zebec Network",
    "H" to "H",
    "ZRO" to "LayerZero",
    "MANA" to "Decentraland",
    "MERL" to "Merlin",
    "AR" to "Arweave",
    "COMP" to "Compound",
    "GLM" to "Golem",
    "LUNC" to "Terra Classic",
    "NEX" to "Nex",
    "XEC" to "eCash",
    "IMX" to "Immutable X",
    "EIGEN" to "EigenLayer",
    "GENIUS" to "Genius",
    "FLUID" to "Fluid",
    "WAL" to "Wal",
    "1INCH" to "1inch",
    "FF" to "FF",
    "KMNO" to "Kamino",
    "RUNE" to "THORChain",
    "CHEEMS" to "Cheems",
    "0G" to "0G",
    "JTO" to "Jito",
    "B" to "B",
    "APE" to "ApeCoin",
    "W" to "Wormhole",
    "ZORA" to "Zora",
    "CVX" to "Convex Finance",
    "BRETT" to "Brett",
    "EGLD" to "Elrond",
    "BARD" to "Bard",
    "ATH" to "Aethir",
    "AMP" to "Amp",
    "RSR" to "Reserve Rights",
    "KITE" to "Kite",
    "SNX" to "Synthetix",
    "DEXE" to "DeXe",
    "ZEN" to "Horizen",
    "AXS" to "Axie Infinity",
    "DYDX" to "dYdX",
    "LPT" to "Livepeer",
    "CHIP" to "Chip",
    "TOSHI" to "Toshi",
    "GRASS" to "Grass",
    "SFP" to "SafePal",
    "SOSO" to "Soso",
    "MX" to "MX Token",
    "PIEVERSE" to "Pieverse",
    "FORM" to "Form",
    "TURBO" to "Turbo",
    "SUPER" to "SuperVerse",
    "KSM" to "Kusama",
    "CTC" to "Creditcoin",
    "MET" to "Met",
    "VELO" to "Velo",
    "COW" to "CoW Protocol",
    "ROSE" to "Oasis Network",
    "CFG" to "Centrifuge",
    "YFI" to "Yearn.finance",
    "KAITO" to "Kaito",
    "BABYDOGE" to "Baby Doge Coin",
    "MOG" to "Mog Coin",
    "ZRX" to "0x",
    "LINEA" to "Linea",
    "AKT" to "Akash Network",
    "ARKM" to "Arkham",
    "USELESS" to "Useless",
    "DEEP" to "Deep",
    "MINA" to "Mina",
    "SAFE" to "Safe",
    "MOVE" to "Movement",
    "EDU" to "Open Campus",
    "ZIL" to "Zilliqa",
    "T" to "Threshold Network",
    "POPCAT" to "Popcat",
    "ALEO" to "Aleo",
    "MEGA" to "Mega",
    "ORDI" to "ORDI",
    "DRIFT" to "Drift",
    "MEW" to "Mew",
    "HOT" to "Holo",
    "ZETA" to "ZetaChain",
    "ME" to "Me",
    "SUSHI" to "SushiSwap",
    "KAVA" to "Kava",
    "UB" to "Ub",
    "NXPC" to "NXPC",
    "PNUT" to "Peanut",
    "BIO" to "Bio",
    "AVNT" to "Avant",
    "BERA" to "Berachain",
    "ICNT" to "ICNT",
    "IRYS" to "Irys",
    "BLUR" to "Blur",
    "PROVE" to "Prove",
    "MOODENG" to "Moo Deng",
    "GMX" to "GMX",
    "COAI" to "CoAI",
    "NMR" to "Numeraire",
    "VTHO" to "VeThor Token",
    "BILL" to "Bill",
    "VANA" to "Vana",
    "SOMI" to "Somi",
    "ALLO" to "Allo",
    "AT" to "At",
    "INIT" to "Init",
    "ZKP" to "ZKP",
    "RED" to "Red",
    "ZIG" to "Zig",
    "DOOD" to "Dood",
    "CPOOL" to "Clearpool",
    "CSPR" to "Casper",
    "BSB" to "BSB",
    "SOPH" to "Sophia",
    "FLUX" to "Flux",
    "CXT" to "CXT",
    "TRIA" to "Tria"
)

val topSymbols = listOf(
    "BTC",
    "ETH",
    "PAXG",
    "XAUT",
    "BNB",
    "XRP",
    "SOL",
    "DOGE",
    "ADA",
    "BCH",
    "TRX",
    "AVAX",
    "DOT",
    "HYPE",
    "XLM",
    "LINK",
    "MATIC",
    "LTC",
    "UNI",
    "TON",
    "SHIBA",
    "PEPE",
    "PUMP",
)